name: Deploy Achados e Perdidos
on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: 'ftp.achadoseperdidosudi.servicos.ws'
        user: 'achadoseperdidos1'
        password: 'Achadoseperdidos@1p'
